### Criar usuário
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "email": "teste2@email.com",
  "senha": "123456",
  "nome": "Teste"
}

### Login
POST http://localhost:3000/api/login
Content-Type: application/json

{
  "email": "teste@email.com",
  "senha": "123456"
}

### Exemplo de resposta

HTTP/1.1 200 OK
{
  "token": "JWT_TOKEN",
  "user": {
    "_id": "{{userId}}",
    "email": "teste@email.com",
    "nome": "Teste"
  }
}

### Usando o token

# Exemplo: buscar usuário com Authorization header
GET http://localhost:3000/api/users/{{userId}}
Authorization: Bearer JWT_TOKEN

###

@userId = 69dd74e5ad91d001f7005d4b

### Buscar usuário
GET http://localhost:3000/api/users/{{userId}}

### Criar texto
POST http://localhost:3000/api/users/{{userId}}/textos
Content-Type: application/json

{
  "titulo": "Meu segundo texto",
  "conteudo": "Conteúdo de teste"
}

### Listar textos
GET http://localhost:3000/api/users/{{userId}}/textos

@textoId = COLE_ID_DO_TEXTO

### Atualizar texto
PUT http://localhost:3000/api/users/{{userId}}/textos/{{textoId}}
Content-Type: application/json

{
  "titulo": "Texto atualizado"
}

### Deletar texto
DELETE http://localhost:3000/api/users/{{userId}}/textos/{{textoId}}

### Atualizar configs
PUT http://localhost:3000/api/users/{{userId}}/configs
Content-Type: application/json

{
  "espacoLinha": 2,
  "corFundo": "#000000",
  "corFonte": "#FFFFFF"
}